name: Opinsys ohjesivusto
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
exclude: [node_modules, assets/styles/styl, package.json, README.md]
highlighter: pygments
permalink: /:categories/:title
baseurl: /opinsys-documentation
variables:
  email: tuki@opinsys.fi
  facebook_page: opinsys
  github_username: opinsys
  home_page: http://www.opinsys.fi
  name: Opinsys Oy
  site_name: ohjeet.opinsys.fi
  twitter_username: opinsys
  youtube_username: opinsys
stylus:
  compress: false
  path: ./assets/styles