name: Opinsys ohjesivusto
markdown: redcarpet
highlighter: pygments
permalink: /:categories/:title
variables:
  email: tuki@opinsys.fi
  facebook_page: opinsys
  github_username: opinsys
  home_page: http://www.opinsys.fi
  name: Opinsys Oy
  site_name: ohjeet.opinsys.fi
  twitter_username: opinsys
  youtube_username: opinsys
stylus:
  compress: false
  path: ./styles
